let programs=[];let current=null;const $=id=>document.getElementById(id);
const audio=$('audio'),playBtn=$('playBtn'),seek=$('seek'),grid=$('programGrid'),search=$('search');
function fmt(s){if(!isFinite(s))return'00:00';s=Math.floor(s);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function setProgram(p,idx){current=p;document.querySelectorAll('.programCard').forEach(c=>c.classList.remove('active'));const card=document.querySelector(`[data-idx="${idx}"]`);if(card)card.classList.add('active');$('cover').src=p.cover;$('cover').alt=p.title;$('category').textContent=p.category||'DG TV';$('title').textContent=p.title;$('speaker').textContent=p.speaker;$('description').textContent=p.description;audio.src=p.audio;seek.value=0;$('currentTime').textContent='00:00';$('duration').textContent='00:00';playBtn.textContent='▶';document.body.classList.remove('playing');$('waBtn').href=p.whatsapp||'https://www.dgtvmusic.com'}
function render(list=programs){grid.innerHTML='';list.forEach((p)=>{const idx=programs.indexOf(p);const btn=document.createElement('button');btn.className='programCard';btn.type='button';btn.dataset.idx=idx;btn.innerHTML=`<img src="${p.cover}" alt="${p.title}"><div class="programText"><strong class="programTitle">${p.title}</strong><span class="programSpeaker">${p.speaker}</span></div>`;btn.addEventListener('click',()=>setProgram(p,idx));grid.appendChild(btn)})}
playBtn.addEventListener('click',async()=>{if(!current&&programs[0])setProgram(programs[0],0);if(audio.paused){try{await audio.play();playBtn.textContent='❚❚';document.body.classList.add('playing')}catch(e){}}else{audio.pause();playBtn.textContent='▶';document.body.classList.remove('playing')}});
audio.addEventListener('timeupdate',()=>{seek.value=audio.duration?(audio.currentTime/audio.duration)*100:0;$('currentTime').textContent=fmt(audio.currentTime);$('duration').textContent=fmt(audio.duration)});
audio.addEventListener('ended',()=>{playBtn.textContent='▶';document.body.classList.remove('playing')});
seek.addEventListener('input',()=>{if(audio.duration)audio.currentTime=(seek.value/100)*audio.duration});
$('shareBtn').addEventListener('click',async()=>{const text=current?`${current.title} - ${current.speaker}`:'DG TV Music Live Radio On Demand';if(navigator.share){navigator.share({title:text,text,url:location.href})}else{navigator.clipboard.writeText(location.href);alert('Link copiato')}});
search.addEventListener('input',()=>{const q=search.value.toLowerCase().trim();render(programs.filter(p=>(p.title+' '+p.speaker+' '+(p.category||'')).toLowerCase().includes(q)))});
fetch('data/programs.json',{cache:'no-store'}).then(r=>r.json()).then(data=>{programs=data;render(programs);if(programs[0])setProgram(programs[0],0)}).catch(()=>{grid.innerHTML='<p style="color:white">Errore nel caricamento programmi.</p>'});
